stages:
  - build
  - release
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:12-alpine
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

dockerise:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u ${user_repo} -p ${token_repo} ${registry}
  script:
    - docker build -t ${registry}:latest -t "${registry}:${CI_COMMIT_TAG}" .
    - docker push ${registry}:${CI_COMMIT_TAG}
    - docker push ${registry}:latest
  after_script:
    - docker logout
  tags:
    - docker
